expose_php = Off
display_errors = Off
log_errors = On
html_errors = Off
file_uploads = Off
post_max_size = 1M
upload_max_filesize = 1M
memory_limit = 256M
max_execution_time = 0
max_input_time = 30
output_buffering = Off
zlib.output_compression = Off
session.use_cookies = Off
